# Backend app

[sources.backend_app]
  type = "syslog"
  mode = "udp"
  address = "0.0.0.0:513"

[transforms.backend_app_parser]
  type = "json_parser"
  inputs = ["backend_app"]
  field = "message"
  drop_field = true
  drop_invalid = false

[sinks.loki_backend_app]
  type = "loki"
  inputs = ["backend_app_parser"]
  endpoint = "http://loki:3100"
  encoding.codec = "json"
  labels.app = "backend"
